version: '3.1'
services:
  db:
    container_name: postgres-server
    image: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=G****101
    - POSTGRES_DB=twitter
    - TZ=America/Sao_Paulo
    volumes: 
    - ./backend/:/usr/src/app
    - /usr/src/app/node_modules
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - type: volume
      source: db-volume
      target: /data/db
  
  app:
    container_name: app
    build: ./backend
    depends_on: 
     - db
    environment: 
     - USER=postgres
     - PASSWORD=G****101
     - DATABASE=twitter
     - HOST=postgres-server
     - DB_PORT=5432
     - WAIT_HOSTS=db:5432
    ports: 
     - 8080:8080

  web:
    container_name: web
    build: ./frontend
    ports: 
     - 8888:8080
    volumes:       
    - ./frontend/:/usr/src/web

volumes:
  db-volume:
