version: '3.1'
services:
  db:
    container_name: postgres-server
    image: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=Gvbrs101
    - POSTGRES_DB=twitter
    - TZ=America/Sao_Paulo
    volumes: 
    - ./backend/:/usr/src/app
    - type: volume
      source: db-volume
      target: /data/db
  
  app:
    container_name: app
    build: ./backend
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    depends_on: 
     - db
    environment: 
     - DIALECT=postgres
     - HOST=postgres-server
     - USER=postgres
     - DATABASE=twitter
     - PASSWORD=Gvbrs101
     - DB_PORT=5432
     - WAIT_HOSTS=db:5432
    ports: 
     - 8080:8080

  web:
    container_name: web
    build: ./frontend
    ports: 
     - 8888:8080
    volumes:       
    - ./frontend/:/usr/src/web

volumes:
  db-volume:
